engines:
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
  phan:
    enabled: true
    config:
      file_extensions: "php"
  shellcheck:
    enabled: true
  markdownlint:
    enabled: true
  fixme:
    enabled: true
    exclude_fingerprints:
    - d3b733a6070d6911055a9868a8c4324e # T-O-D-O on R-E-A-D-M-E.md
    - 3b8460fab6956f12bd2db9db7e5c7f90 # T-O-D-O on T-O-D-O.md
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php

ratings:
  paths:
  - "**.php"
  - "**.js"
  - "**.css"

exclude_paths:
  - "vendor/*"
  - "public/web/jquery.min.js"
  - "public/web/bootstrap/js/bootstrap.min.js"
  - "public/web/bootstrap/css/bootstrap.min.css"
  - "public/web/bootstrap/fonts/*"
